// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("http://localhost:8080/HadarDallal_TalBenHamo_YarinAkiva/index.jsp");
    driver.manage().window().setSize(new Dimension(699, 728));
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("tal");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("Hello, tal"));
    driver.findElement(By.linkText("Go Back")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("hadar");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.getTitle(), is("Submission Result"));
    driver.findElement(By.linkText("Go Back")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("yarin");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("p")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector("p")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("Hello, yarin"));
    driver.findElement(By.linkText("Go Back")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("moshe");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("Hello, moshe"));
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.linkText("Go Back")).click();
    driver.findElement(By.linkText("About Us")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("This is a simple JSP web application."));
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.cssSelector("#name")).sendKeys("moshe");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.linkText("Go Back")).click();
  }
}
